const galleryItems = [
    { id: 1, path: 'images/myself.jpg', 
    title: 'Myself',
    description: 'Self portrait in Washington', 
    likes: 0 },
    { id: 2, path: 'images/benji.jpg', 
    title: 'My cute dog',
    description: 'Photo of Benji!', 
    likes: 0 },
    { id: 3, path: 'images/hal.jpg', 
    title: 'Hal',
    description: 'My partner Hal in the Tetons!', 
    likes: 0 },
    { id: 4, path: 'images/tb.jpg', 
    title: 'My band, Tacklebox',
    description: 'My band, tacklebox', 
    likes: 0 },
    { id: 5, path: 'images/adam.jpg', 
    title: 'adam',
    description: 'My roomate Adam', 
    likes: 0 },
    { id: 6, path: 'images/art.jpg', 
    title: 'art',
    description: 'My favorite piece of art that I have made', 
    likes: 0 },
    { id: 7, path: 'images/iceland.jpg', 
    title: 'iceland',
    description: 'Horses in Iceland', 
    likes: 0 },
    { id: 8, path: 'images/coffee.jpg', 
    title: 'coffee',
    description: 'Latte art for my day job!', 
    likes: 0 },
    { id: 8, path: 'images/eclipse.jpg', 
    title: 'eclipse',
    description: 'Total solar eclipse in Wyoming!', 
    likes: 0 },
        { id: 10, path: 'images/family.jpg', 
    title: 'family',
    description: 'Family!', 
    likes: 0 },
    { id: 11, path: 'images/redwoods.jpg', 
    title: 'tree',
    description: 'Redwoods!', 
    likes: 0 },
    { id: 12, path: 'images/cave.jpg', 
    title: 'cave',
    description: 'Cave diving!', 
    likes: 0 }
];

module.exports = galleryItems;
